project_id = "uadwnxqcpfcrpuyetpaw"

[functions.pluggy-auto-sync]
verify_jwt = false

[functions.pluggy-webhook]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.clicksign-webhook]
verify_jwt = false

[functions.auth-proxy]
verify_jwt = false
